routes/web.php
<?php


//HOME
Route::get('/', 'HomeController@index')->name('home');

//PUBLIC

Route::group(['prefix' => 'public'],function(){

    //LOGIN
    Route::post('login','Auth\LoginController@login')->name('login'); 
    Route::get('logout', 'Auth\LoginController@logout')->name('logout');

    //JUNTA
    Route::get('junta/public','JuntaController@junta_public')->name('junta.public.index');

    //HOME
    Route::get('home/noticia/show/{noticia_id}','HomeController@show')->name('home.noticia.show');
    Route::get('home/noticias/list','HomeController@list')->name('home.noticias.list');

    //SEARCH
    Route::get('search/get/{string?}','SearchController@get')->name('search.get');
    Route::get('search/show/{pos_id}','SearchController@show')->name('search.show');

    //QUIENES SOMOS (INDEX 2)
    Route::get('quienes-somos','QuienesSomosController@index_public')->name('quienes-somos.index2');

    //contactos
    Route::post('contactos/send_message','ContactoController@send_message')->name('contactos.send_message');
    Route::get('contactos','ContactoController@index')->name('contactos.index');

    //documents
    Route::get('noticias/show_document/{id}/{nombre}','NoticiaController@show_document')
        ->name('public.document-pos.show');

    //SGSST
    Route::get('sgsst/index','SgsstController@index')->name('sgsst.index');

    //PLAN DE ACCION
    Route::get('plan_accion/index','PlanAccionController@index')->name('plan_accion.index');
    //QUIENES SOMOS (INDEX 2)
    Route::get('post_email/{pos_id}','NoticiaController@post_email')->name('post_email.publicaciones');

    Route::get('normativa_public','NormativaController@index_public')->name('normativa_public.index');



});

//ADMIN

Route::group(['prefix' => 'admin'],function(){

    //CORREOS

    //Route::post('correos/upload','CorreoController@upload')->name('correos.upload');
    Route::get('correos/search/{elemento?}','CorreoController@search');
    Route::get('correos/list','CorreoController@list');
    Route::resource('correos','CorreoController');
    Route::get('correos/destroy/{correo_id}','CorreoController@destroy');
    
    //OTROS
    Route::get('otros/delete_doc/{obj_id}','OtroController@delete_doc')->name('otros.delete-pos');
    Route::get('otros/index','OtroController@index')->name('otros.index');
    Route::get('otros/edit_pos/{pos_id}','OtroController@editar_pos')->name('otros.edit_pos');
    Route::get('otros/edit_element/{element_id}','OtroController@editar_element')->name('otros.edit_element');
    Route::put('otros/update/{id}','OtroController@update')->name('otros.update');
    Route::get('otros/{object_id}/ver/{nombre}','OtroController@show_document')->name('document-pos.show');
 
    //NORMATIVA
    Route::get('normativa/delete_img/{normativa_id}','NormativaController@delete_image')->name('normativa.delete_img');
    Route::get('normativa/delete_doc/{obj_id}','NormativaController@delete_doc')->name('normativa.delete-pos');
    Route::resource('normativa','NormativaController');
    Route::get('normativa/{object_id}/ver/{nombre}','NormativaController@show_document')->name('document-normativa.show');
    Route::get('normativa/destroy/{normativa_id}','NormativaController@destroy')->name('normativa.destroy');
    Route::get('normativa/get_documento/{pos_id}','NormativaController@get_documento')->name('normativa.get_document');
    
    //ESTATUTOS
    Route::get('estatutos/delete_img','EstatutosController@delete_image')->name('estatutos.delete_img');
    Route::resource('estatutos','EstatutosController');

    //JUNTA
    Route::resource('junta','JuntaController');
    Route::get('junta/destroy/{integrante_id}','JuntaController@destroy')->name('junta.destroy');
    
    //EMPRESA
    Route::resource('empresa','EmpresaController');
    
    //HISTORIA
    Route::get('historia/delete_img','HistoriaController@delete_image')->name('historia.delete_img');
    Route::resource('historia','HistoriaController');
    
    //USER
    Route::get('users/edit_pass/{user_id}','UserController@edit_pass')->name('users.edit_pass');
    Route::post('users/update_pass','UserController@update_pass')->name('users.update_pass');
    Route::resource('users','UserController');
    Route::get('users/{user_id}/destroy','UserController@destroy')->name('users.destroy');
    
    //NOTICIAS
    Route::get('noticia/delete_doc/{obj_id}','NoticiaController@delete_doc')->name('noticia.delete-pos');
    Route::get('noticia/delete_img/{noticia_id}','NoticiaController@delete_image')->name('noticia.delete_img');
    Route::get('noticias/send/{noticia_id}','NoticiaController@send')->name('noticias.send');
    Route::resource('noticias','NoticiaController');
    Route::get('noticias/{object_id}/ver/{nombre}','NoticiaController@show_document')->name('document-noticia.show');
    Route::get('noticias/get_document/{pos_id}','NoticiaController@get_document')->name('noticias.get_document');
    Route::get('noticias/destroy/{noticia_id}','NoticiaController@destroy')->name('noticias.destroy');
   
    //DASHBOARD
    Route::get('dash','DashboardController@index')->name('dash.index');
    
    //BANNER
    Route::resource('banner','BannerController');
    Route::get('banner/destroy/{banner_id}','BannerController@destroy')->name('banner.destroy');
    Route::get('banner/get_banner/{banner_id}','BannerController@get_banner')->name('banner.get_banner');

    //LINKS
    Route::resource('links','LinkController');
    Route::post('links/actualizar','LinkController@actualizar')->name('links.actualizar');
    Route::get('links/destroy/{link_id}','LinkController@destroy')->name('link.destroy');
    
    //QUIENES SOMOS
    Route::resource('quienes_somos','QuienesSomosController');

    //HISTORIA
    Route::resource('historia','HistoriaController');

    //PERFIL
    Route::get('perfil','HomeController@get_perfil')->name('perfil');

    //INSTITUCION
    Route::get('institucion/create','InstitucionController@create')->name('institucion.create');
    Route::post('institucion','InstitucionController@store')->name('institucion.store');

    //HORIZONTE
    Route::put('horizonte/{horizonte}','HorizonteController@update')->name('horizonte.update');

    //ESTATUTOS
    Route::get('estatutos/delete_doc/{obj_id}','EstatutosController@delete_doc')->name('estatutos.delete-pos');
    Route::get('estatutos/get_document/{pos_id}','EstatutosController@get_document')->name('estatutos.get_document');
    Route::get('estatutos/{object_id}/ver/{nombre}','EstatutosController@show_document')->name('document-estatutos.show');

});

app/Http/Controllers/NoticiaController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\NoticiaCreateRequest;
use App\Http\Requests\NoticiaUpdateRequest;
use Illuminate\Support\Facades\DB;
use App\Traits\NoticiaTrait;
use Illuminate\Http\Request;
use App\Mail\SendNoticia;
use App\Traits\HomeTrait;
use App\Traits\DocTrait;
use App\Noticia;
use App\Empresa;
use App\Correo;
use App\Pos;

use Storage;
use Flash;
use Mail;

//use App\Traits\HomeTrait;

class NoticiaController extends Controller
{
    use NoticiaTrait;
    use HomeTrait;
    use DocTrait;

    protected $noticia;
    protected $noticias;
	protected $banner;
	protected $empresa;
	protected $links;

    public  function __construct()
    {    
        $this->noticia = new Pos();
        $this->noticia->tipo_pos_id = 1; //noticia
        $this->middleware('auth',['except' => ['post_email']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $noticias = Pos::orderBy('updated_at','desc')
            ->where('tipo_pos_id',1)
            ->get();

        return view('admin.noticias.index')
            ->with('noticias', $noticias)
            ->with('info',null)
            ->with('ruta_view',rutas_view('home'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.noticias.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(NoticiaCreateRequest $request)
    {
        $this->noticia->titulo   = $request->titulo;
        $this->noticia->texto    = $request->texto;
        $this->noticia->user_create_id  = 1;
        
        if ( $request->hasFile('img_file') ){
            $data = $this->save_img($request);
        }

        if ( $request->hasFile('doc_file') ){
            $doc = $this->save_doc($request, 'noticias');
            $this->noticia->doc_name = $doc['nombre'];
            $this->noticia->doc_ruta = $doc['ruta'];
        }

        $this->noticia->save();

        session()->flash('success','Se creó la noticia exitosamente !!!');

        return redirect()->route('noticias.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Noticia  $noticia
     * @return \Illuminate\Http\Response
     */
    public function show($noticia_id)
    {    
        $noticia = Pos::find($noticia_id);
        return view('admin.noticias.show')
            ->with('noticia',$noticia);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Noticia  $noticia
     * @return \Illuminate\Http\Response
     */
    public function edit($noticia_id)
    {
        $noticia = Pos::find($noticia_id);
        
        return view('admin.noticias.edit')
            ->with('noticia',$noticia);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Noticia  $noticia
     * @return \Illuminate\Http\Response
     */
    public function update(NoticiaUpdateRequest $request,$noticia_id)
    {
        $this->noticia = Pos::find($noticia_id);
        $this->noticia->fill($request->all());

        if ( $request->hasFile('img_file') ){
            $this->delete_img();
            $this->save_img($request);
        }

        if ( $request->hasFile('doc_file') ){

            $this->delete_doc($this->noticia->doc_ruta);
            $doc = $this->save_doc($request, 'noticias');
            $this->noticia->doc_name = $doc['nombre'];
            $this->noticia->doc_ruta = $doc['ruta'];
        }

        if ( ! $this->noticia->isDirty() ) {

            session()->flash('info','Ningun cambio en registro');    
            return redirect()->route('noticias.edit',$noticia_id);
        }

        $this->noticia->user_update_id  = 1;

        $this->noticia->save();

        session()->flash('success','Se editó la noticia exitosamente !!!');
        return redirect()->route('noticias.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Noticia  $noticia
     * @return \Illuminate\Http\Response
     */
    public function destroy($noticia_id)
    {
        $this->pos = Pos::find($noticia_id);
        if ( $this->pos->img_ruta ){
            $this->delete_img();
        }

        if ( $this->pos->doc_ruta ){
            $this->delete_doc($this->pos->doc_ruta);
        }
        $this->pos->delete();

        session()->flash('success','Se eliminó la noticia exitosamente !!!');
        return redirect()->route('noticias.index');
    }

    public function send($noticia_id)
    {
        $noticia = Pos::find($noticia_id);
        $noticia->texto = contador_palabras($noticia->texto,40);

        $mails = Correo::all()->toArray();
        $collection = collect($mails);
        $collection_emails = $collection->pluck('correo');

        Mail::to($collection_emails)->send(
            new SendNoticia($noticia)
        );

        session()->flash('success','Mensaje enviado !!!');
        return redirect()->route('noticias.index');
    }

    public function post_email($pos_id)
    {
        $pos = hp_get_noticia($pos_id);

        return view('public.publicaciones.post_email')
            ->with('pos',$pos)
            ->with('data',getDataIniHp());
    }
    
    public function delete_doc($obj_id)
    {
        $pos = Pos::find($obj_id);
        if($pos){
            $this->delete_doc($pos->doc_ruta);
            $pos->doc_name = '';
            $pos->doc_ruta = '';
            $pos->save();
        }
        return redirect()->route('noticias.edit',$obj_id);    
    }

    public function delete_image($noticia_id)
    {
        $noticia = Pos::find($noticia_id);
        $this->delete_img($noticia->img_ruta);
        $noticia->img_ruta = null;
        $noticia->img_name = null;
        $noticia->save();

        session()->flash('success','Se eliminó la imagen !!!');
        return redirect()->route('noticias.edit',$noticia->id);
    }

}

resources/views/admin/noticias/create.blade.php
@extends('admin.template.main')
@section('title','Noticias')

@section('contenido')

<br>
<div class="card">
  <div class="card-body">
    <div class="card-title">
        <h4 style="display:contents;">Noticias</h4>
				<a href="javascript:window.history.back();"class="btn btn-success btn-sm" style="display:inline;float:right;">
            Volver
        </a>
		<hr>
    </div>
    
	<div class="col-md-8">

		@include('librerias.error')
	
		<form method="POST" action="{{route('noticias.store')}}" enctype="multipart/form-data">

		@csrf

		<div class="form-group">
			<label for="">Titulo *</label>
			<input type="text" class="form-control form-control-sm" name="titulo" 
						 aria-describedby="Titulo" placeholder="Mi nueva noticia">
			<small id="emailHelp" class="form-text text-muted">Escriba un titulo para su noticia.</small>
		</div>

		<div class="form-group">
			<label for="exampleFormControlFile1">Imagen</label>
    		<input type="file" class="form-control-file" name="img_file">
		</div>

		<div class="form-group">
			<label for="">Contenido</label>
			<textarea class="form-control" name="texto" id="" cols="30" rows="10"></textarea>
			<small id="" class="form-text text-muted">Ingrese el texto de su noticia.</small>
		</div>

		<div class="form-group">
			<label for="">Archivo adjunto</label>
    		<input type="file" class="form-control-file" name="doc_file">

		</div>

		<button type="submit" class="btn btn-primary">Crear</button>

		</div>
		</form>
	</div>

  </div>
</div>

<script>
    CKEDITOR.replace( 'texto' );
</script>

@endsection

resources/views/admin/noticias/edit.blade.php
@extends('admin.template.main')
@section('title','Noticias')

@section('contenido')

<br>
<div class="card">
  <div class="card-body">
    <div class="card-title">
        <h4 style="display:inline;">Noticias</h4>
				<a href="javascript:window.history.back();"class="btn btn-success btn-sm" 
					style="display:inline;float:right;">
            Volver
        </a>
		<hr>
    </div>
    
	<div class="col-md-8">
		@include('librerias.error')

		<form method="POST" action="{{route('noticias.update',$noticia)}}" enctype="multipart/form-data">

		<input type="hidden" name="_method" value="PUT">

		@csrf

		<div class="form-group">
			<label for="">Titulo *</label>
			<input type="text" value="{{$noticia->titulo}}" class="form-control" 
						 name="titulo" aria-describedby="Titulo" placeholder="Mi nueva noticia">
			<small name="titulo" class="form-text text-muted">Escriba un titulo para su noticia.</small>
		</div>
		<div class="form-group">

			@if($noticia->img_ruta)
				<img src="{{asset($noticia->img_ruta)}}" width="400">
				<br><br>
				<dd> {{ $noticia->img_name }}
					<a href="{{ route('noticia.delete_img',$noticia->id) }}" 
						onclick="return confirm('¿Esta seguro de borra el documento?')"
						class="btn btn-danger btn-sm">Eliminar</a>
				</dd>

			@endif
	
			<label for="">Imagen</label>
    		<input type="file" class="form-control-file" name="img_file">
		</div>
		<div class="form-group">
			<label for="">Contenido</label>
			<textarea class="form-control" name="texto" id="" cols="30" rows="10">{{ $noticia->texto }}</textarea>
			<small id="" class="form-text text-muted">Ingrese el texto de su noticia.</small>
		</div>
		
		<div class="form-group">
			@if($noticia->doc_ruta)
					<label for="">Archivo adjunto: 
					<a href="{{ route('document-noticia.show',[$noticia->id,$noticia->doc_name]) }}" target="_bñank">
							{{ $noticia->doc_name }}</a></label>

					<a href="{{ route('noticia.delete-pos',$noticia->id) }}" 
						onclick="return confirm('¿Esta seguro de borra el documento?')"
						class="btn btn-danger btn-sm">Eliminar</a>
				@endif

				<input type="file" class="form-control-file" name="doc_file">
		</div>

		<button type="submit" class="btn btn-primary">Guardar cambios</button>

		</div>
		</form>
	</div>

  </div>
</div>

<script>
    CKEDITOR.replace( 'texto' );
</script>

@endsection

resources/views/admin/noticias/index.blade.php
@extends('admin.template.main')
@section('title','Noticias')

@section('contenido')

<br>
<div class="card">
  <div class="card-body">
    <div class="card-title">
        <h5 style="display:inline;">Noticias</h5>

        <a href="{{ route('noticias.create') }}" class="btn btn-danger btn-sm float-right"
            style="display:inline; margin-left:5px;">
            Crear noticia</a>
        <a href="javascript:window.history.back();"class="btn btn-success btn-sm" style="display:inline;float:right;">
            Volver
        </a>
        <hr>
        <p>
            @include('librerias.error')
        </p>
    </div>
    <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Imagen</th>
                <th>Titulo</th>
                <th>Estado</th>
                <th>Creación</th>
                <th>Actualización</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach($noticias as $noticia)
            <tr>
                @if($noticia->img_ruta)
                <td><img src="{{asset($noticia->img_ruta)}}" width="100"></td>
                @else
                <td>N/A</td>
                @endif
                <td>{{ $noticia->titulo }}</td>
                <td>{{ $noticia->estado }}</td>
                <td>{{ $noticia->created_at }}</td>
                <td>{{ $noticia->updated_at }}</td>
                <td>
                    <a href="{{ route('noticias.show',$noticia->id) }}" 
                            class="btn btn-outline-secondary btn-sm">Ver</a>

                    <a href="{{ route('noticias.edit',$noticia->id) }}" 
                            class="btn btn-outline-success btn-sm">Editar</a>

                    <a href="{{ route('noticias.send',$noticia->id) }}" 
                            class="btn btn-outline-primary btn-sm">Enviar</a>

                    <a href="{{ route('noticias.destroy',$noticia->id) }}" 
                            class="btn btn-outline-danger btn-sm" 
                            onclick="return confirm('¿ Esta seguro de eliminar la noticia ?')">
                        Eliminar
                    </a>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

  </div>
</div>



    <script>

        $(document).ready(function() {
            $('#example').DataTable({
                "paging": true,
                "searching": true,
                "order": [[ 4, 'desc' ]]
            });
        } );


    
    </script>

@endsection

resources/views/admin/noticias/show.blade.php
@extends('admin.template.main')
@section('title','Noticia')

@section('contenido')
<br>
<div class="card">
  <div class="card-body">
    <div class="card-title">
		<div class="ml-4 mr-4">
        <h4 style="display:inline;">Noticia</h4>
        <a href="javascript:window.history.back();"class="btn btn-success btn-sm" style="display:inline;float:right;">
            Volver
        </a>
		<hr>
		<dt style="display:inline;">Titulo:</dt>
		<dd style="display:inline;"> {{ $noticia->titulo }}</dd>
    <br><br>
    @if($noticia->img_ruta)
      <img src="{{asset($noticia->img_ruta)}}" width="500" height="300">
      <br>
      <dd> nombre: {{ $noticia->img_name }}</dd>
    @endif
		<dt>Contenido</dt>
		<dd class="text-justify"> {!! $noticia->texto !!}</dd>
    @if($noticia->doc_ruta)
		  <dt><a href="{{ route('document-noticia.show',[$noticia->id,$noticia->doc_name]) }}" target="_blank">{{ $noticia->doc_name }}</a></dt>
    @endif
		</div>
    </div>
    <br>


  </div>
</div>



    <script>

        $(document).ready(function() {
            $('#example').DataTable({
                "paging": false,
                "searching": false
            });
        } );


    
    </script>



@endsection