routes/web.php
<?php


//HOME
Route::get('/', 'HomeController@index')->name('home');

//PUBLIC

Route::group(['prefix' => 'public'],function(){

    //LOGIN
    Route::post('login','Auth\LoginController@login')->name('login'); 
    Route::get('logout', 'Auth\LoginController@logout')->name('logout');

    //JUNTA
    Route::get('junta/public','JuntaController@junta_public')->name('junta.public.index');

    //HOME
    Route::get('home/noticia/show/{noticia_id}','HomeController@show')->name('home.noticia.show');
    Route::get('home/noticias/list','HomeController@list')->name('home.noticias.list');

    //SEARCH
    Route::get('search/get/{string?}','SearchController@get')->name('search.get');
    Route::get('search/show/{pos_id}','SearchController@show')->name('search.show');

    //QUIENES SOMOS (INDEX 2)
    Route::get('quienes-somos','QuienesSomosController@index_public')->name('quienes-somos.index2');

    //contactos
    Route::post('contactos/send_message','ContactoController@send_message')->name('contactos.send_message');
    Route::get('contactos','ContactoController@index')->name('contactos.index');

    //documents
    Route::get('noticias/show_document/{id}/{nombre}','NoticiaController@show_document')
        ->name('public.document-pos.show');

    //SGSST
    Route::get('sgsst/index','SgsstController@index')->name('sgsst.index');

    //PLAN DE ACCION
    Route::get('plan_accion/index','PlanAccionController@index')->name('plan_accion.index');
    //QUIENES SOMOS (INDEX 2)
    Route::get('post_email/{pos_id}','NoticiaController@post_email')->name('post_email.publicaciones');

    Route::get('normativa_public','NormativaController@index_public')->name('normativa_public.index');



});

//ADMIN

Route::group(['prefix' => 'admin'],function(){

    //CORREOS

    //Route::post('correos/upload','CorreoController@upload')->name('correos.upload');
    Route::get('correos/search/{elemento?}','CorreoController@search');
    Route::get('correos/list','CorreoController@list');
    Route::resource('correos','CorreoController');
    Route::get('correos/destroy/{correo_id}','CorreoController@destroy');
    
    //OTROS
    Route::get('otros/delete_doc/{obj_id}','OtroController@delete_doc')->name('otros.delete-pos');
    Route::get('otros/index','OtroController@index')->name('otros.index');
    Route::get('otros/edit_pos/{pos_id}','OtroController@editar_pos')->name('otros.edit_pos');
    Route::get('otros/edit_element/{element_id}','OtroController@editar_element')->name('otros.edit_element');
    Route::put('otros/update/{id}','OtroController@update')->name('otros.update');
    Route::get('otros/{object_id}/ver/{nombre}','OtroController@show_document')->name('document-pos.show');
 
    //NORMATIVA
    Route::get('normativa/delete_img/{normativa_id}','NormativaController@delete_image')->name('normativa.delete_img');
    Route::get('normativa/delete_doc/{obj_id}','NormativaController@delete_doc')->name('normativa.delete-pos');
    Route::resource('normativa','NormativaController');
    Route::get('normativa/{object_id}/ver/{nombre}','NormativaController@show_document')->name('document-normativa.show');
    Route::get('normativa/destroy/{normativa_id}','NormativaController@destroy')->name('normativa.destroy');
    Route::get('normativa/get_documento/{pos_id}','NormativaController@get_documento')->name('normativa.get_document');
    
    //ESTATUTOS
    Route::get('estatutos/delete_img','EstatutosController@delete_image')->name('estatutos.delete_img');
    Route::resource('estatutos','EstatutosController');

    //JUNTA
    Route::resource('junta','JuntaController');
    Route::get('junta/destroy/{integrante_id}','JuntaController@destroy')->name('junta.destroy');
    
    //EMPRESA
    Route::resource('empresa','EmpresaController');
    
    //HISTORIA
    Route::get('historia/delete_img','HistoriaController@delete_image')->name('historia.delete_img');
    Route::resource('historia','HistoriaController');
    
    //USER
    Route::get('users/edit_pass/{user_id}','UserController@edit_pass')->name('users.edit_pass');
    Route::post('users/update_pass','UserController@update_pass')->name('users.update_pass');
    Route::resource('users','UserController');
    Route::get('users/{user_id}/destroy','UserController@destroy')->name('users.destroy');
    
    //NOTICIAS
    Route::get('noticia/delete_doc/{obj_id}','NoticiaController@delete_doc')->name('noticia.delete-pos');
    Route::get('noticia/delete_img/{noticia_id}','NoticiaController@delete_image')->name('noticia.delete_img');
    Route::get('noticias/send/{noticia_id}','NoticiaController@send')->name('noticias.send');
    Route::resource('noticias','NoticiaController');
    Route::get('noticias/{object_id}/ver/{nombre}','NoticiaController@show_document')->name('document-noticia.show');
    Route::get('noticias/get_document/{pos_id}','NoticiaController@get_document')->name('noticias.get_document');
    Route::get('noticias/destroy/{noticia_id}','NoticiaController@destroy')->name('noticias.destroy');
   
    //DASHBOARD
    Route::get('dash','DashboardController@index')->name('dash.index');
    
    //BANNER
    Route::resource('banner','BannerController');
    Route::get('banner/destroy/{banner_id}','BannerController@destroy')->name('banner.destroy');
    Route::get('banner/get_banner/{banner_id}','BannerController@get_banner')->name('banner.get_banner');

    //LINKS
    Route::resource('links','LinkController');
    Route::post('links/actualizar','LinkController@actualizar')->name('links.actualizar');
    Route::get('links/destroy/{link_id}','LinkController@destroy')->name('link.destroy');
    
    //QUIENES SOMOS
    Route::resource('quienes_somos','QuienesSomosController');

    //HISTORIA
    Route::resource('historia','HistoriaController');

    //PERFIL
    Route::get('perfil','HomeController@get_perfil')->name('perfil');

    //INSTITUCION
    Route::get('institucion/create','InstitucionController@create')->name('institucion.create');
    Route::post('institucion','InstitucionController@store')->name('institucion.store');

    //HORIZONTE
    Route::put('horizonte/{horizonte}','HorizonteController@update')->name('horizonte.update');

    //ESTATUTOS
    Route::get('estatutos/delete_doc/{obj_id}','EstatutosController@delete_doc')->name('estatutos.delete-pos');
    Route::get('estatutos/get_document/{pos_id}','EstatutosController@get_document')->name('estatutos.get_document');
    Route::get('estatutos/{object_id}/ver/{nombre}','EstatutosController@show_document')->name('document-estatutos.show');

});

app/Http/Controllers/JuntaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\JuntaUpdateRequest;
use App\Http\Requests\JuntaCreateRequest;
use App\Traits\JuntaTrait;
use App\Cargo;
use App\User;
use Auth;
use DB;

class JuntaController extends Controller
{
    use JuntaTrait;
    protected $junta;
    protected $integrante;
    protected $links;
    protected $empresa;


    public function __construct()
    {
        $this->integrante = new User();
        $this->middleware('auth', ["except" => ["junta_public"]]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->junta = User::where('rol','Junta directiva')
            //->where('estado','Activo')
            ->orderBy('posicion','asc')
            ->get();

        return view('admin.junta.index')
            ->with('junta',$this->junta);
    }

    public function junta_public()
    {
        $this->junta = User::where('rol','Junta directiva')
            ->where('estado','Activo')
            ->orderBy('posicion','asc')
            ->get();

        return view('public.junta.index')
            ->with('junta',$this->junta)
            ->with('data',getDataIniHp());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cargos = Cargo::orderBy('nombre')->get();
        $roles  = getEnumValues('users','rol');
        $integrantes = User::where('estado','Activo')
            ->where('rol','Junta directiva')
            ->orderBy('posicion','asc')
            ->get();

        return view('admin.junta.create')
            ->with('cargos',$cargos)
            ->with('roles',$roles)
            ->with('integrantes',$integrantes);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(JuntaCreateRequest $request)
    {
        DB::beginTransaction();
        try {
            $this->agregarPosicionJt($request->position);

            $this->integrante->fill($request->all()); 
    
            $this->integrante->rol = 'Junta directiva';
            $this->integrante->user_create_id = Auth::user()->id;
            $this->integrante->save();
    
            DB::commit();

            session()->flash('success','Se creó el registro exitosamente !!!');
            return redirect()->route('junta.index');
        }
        catch(\Exception $e) {
            DB::rollback();

            session()->flash('danger','Se presento un error =(');
            return redirect()->route('junta.create');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($integrante_id)
    {
        $this->integrante = User::find($integrante_id);

        return view('admin.junta.show')
            ->with('integrante',$this->integrante);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $integrante = User::find($id);
        $cargos     = Cargo::orderBy('nombre')->get();
        $roles      = getEnumValues('users','rol');

        $integrantes = User::where('estado','Activo')
            ->where('rol','Junta directiva')
            ->orderBy('posicion','asc')
            ->get();

        return view('admin.junta.edit')
            ->with('integrantes',$integrantes)
            ->with('integrante',$integrante)
            ->with('cargos',$cargos)
            ->with('roles',$roles);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $integrante_id)
    {
        DB::beginTransaction();

        try {          
            $integrante = User::find($integrante_id);
            $bandera = 0;

            $this->integrante = User::find($integrante_id);
            $this->integrante->fill($request->all()); 

            if(isset($request->position) && $request->position != $integrante->posicion){
            
                $this->actualizarPosicionJt($request->position, $integrante_id);
                $bandera = 1;
            } 

            if ( ! $this->integrante->isDirty() && $bandera == 0) {
                session()->flash('info','Ningun cambio en registro');    
                return redirect()->route('junta.edit',$integrante_id);
            }
            $this->integrante->user_update_id = Auth::user()->id;
            $this->integrante->save();

            DB::commit();

            session()->flash('success','Se editó el registro exitosamente !!!');
            return redirect()->route('junta.index');
        } 
        catch (\Exception $e) {
            DB::rollback();
            session()->flash('danger','Error al actualizar !!! '.$e->getMessage());
            return redirect()->route('junta.edit',$integrante_id);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($integrante_id)
    {
        DB::beginTransaction();
        try{
            $this->integrante = User::find($integrante_id);
            $this->eliminarPosicionJt($this->integrante->posicion);
            $this->integrante->delete();

            DB::commit();
    
            session()->flash('success','Se eliminó el registro exitosamente !!!');
            return redirect()->route('junta.index');        

        } catch (\Exception $e){
            DB::commit();
            session()->flash('error','Error al eliminar : '.$e->getMessage());
            return redirect()->route('junta.index');        
        }
    }


}

resources/views/admin/junta/create.blade.php
@extends('admin.template.main')
@section('title','Junta directiva')

@section('contenido')

<br>
<div class="card">
  <div class="card-body">
    <div class="card-title">
        <h4 style="display:inline;">Integrante junta directiva</h4>
				<a href="javascript:window.history.back();"class="btn btn-success btn-sm" 
					style="display:inline;float:right;">
            Volver
        </a>
		<hr>
    </div>
    
	<div class="col-md-8">
		@include('librerias.error')

		<form method="POST" action="{{route('junta.store')}}">

        @csrf

		<div class="form-group">
			<label for="">Nombres *</label>
            <input type="text" value="" class="form-control form-control-sm" 
                name="nombres" aria-describedby="Titulo">
			<small name="" class="form-text text-muted">Escriba el nombre completo.</small>
        </div>
		<div class="form-group">
			<label for="">Apellidos *</label>
            <input type="text" value="" class="form-control form-control-sm" 
                name="apellidos" aria-describedby="Titulo">
			<small name="" class="form-text text-muted">Escriba los apellido.</small>
        </div>
		<div class="form-group">
			<label for="">Teléfono</label>
            <input type="text" value="" class="form-control form-control-sm" 
                name="telefono" aria-describedby="Titulo">
			<small name="" class="form-text text-muted">Escriba los apellido.</small>
        </div>
        
		<div class="form-group">
			<label for="">Email</label>
            <input type="email" value="" class="form-control form-control-sm" name="email" 
                aria-describedby="Titulo">
			<small name="" class="form-text text-muted">Escriba el email.</small>
        </div>
        <div class="form-group">
			<label for="">Cargo</label>
            <select name="cargo_id" class="form-control form-control-sm">
                <option selected disabled></option>
                @foreach($cargos as $cargo)
                    <option value="{{ $cargo->id }}">{{ $cargo->nombre }}</option>
                @endforeach
            </select>
			<small name="" class="form-text text-muted">Seleccione un cargo, ej: Presidente.</small>
        </div>
        
        <div class="form-group">
			<label for="">Institución</label>
            <input type="text" value="" class="form-control form-control-sm" 
                name="institucion" aria-describedby="Titulo" >
			<small name="" class="form-text text-muted">Escriba el nombre de la institución a la que pertenece.</small>
        </div>
        <div class="form-group">
			<label for="">Posición</label>
            <select name="position" class="form-control form-control-sm">
                @php
                    $count = 1
                @endphp
                <option value="{{$count}}">Al comienzo</option>
                @foreach($integrantes as $integrante)
                    <option value="{{++$count}}">{{ 'Despues de: ('.$integrante->cargo->nombre.') '.$integrante->nombres.
                        ' '.$integrante->apellidos}}</option>
                @endforeach
            </select>
			<small name="" class="form-text text-muted">Seleccione la posición.</small>
        </div>



		<button type="submit" class="btn btn-primary">Crear</button>

		</div>
		</form>
	</div>

  </div>
</div>

@endsection

resources/views/admin/junta/edit.blade.php
@extends('admin.template.main')
@section('title','Junta directiva')

@section('contenido')

<br>
<div class="card">
  <div class="card-body">
    <div class="card-title">
        <h4 style="display:inline;">Integrante junta directiva</h4>
				<a href="javascript:window.history.back();"class="btn btn-success btn-sm" 
					style="display:inline;float:right;">
            Volver
        </a>
		<hr>
    </div>
    
	<div class="col-md-8">
		@include('librerias.error')

		<form method="POST" action="{{route('junta.update',$integrante)}}">

		<input type="hidden" name="_method" value="PUT">

        @csrf

		<div class="form-group">
			<label for="">Nombres *</label>
            <input type="text" value="{{$integrante->nombres}}" class="form-control form-control-sm" 
                name="nombres" aria-describedby="Titulo" placeholder="Mi nueva noticia">
			<small name="" class="form-text text-muted">Escriba el nombre completo.</small>
        </div>
		<div class="form-group">
			<label for="">Apellidos *</label>
            <input type="text" value="{{$integrante->apellidos}}" class="form-control form-control-sm" 
                name="apellidos" aria-describedby="Titulo" placeholder="Mi nueva noticia">
			<small name="" class="form-text text-muted">Escriba los apellido.</small>
        </div>
		<div class="form-group">
			<label for="">Teléfono</label>
            <input type="text" value="{{$integrante->telefono}}" class="form-control form-control-sm" 
                name="telefono" aria-describedby="Titulo" placeholder="Mi nueva noticia">
			<small name="" class="form-text text-muted">Escriba los apellido.</small>
        </div>
        
		<div class="form-group">
			<label for="">Email</label>
            <input type="email" value="{{$integrante->email}}" class="form-control form-control-sm" name="email" 
                aria-describedby="Titulo" placeholder="Mi nueva noticia">
			<small name="" class="form-text text-muted">Escriba el email.</small>
        </div>
        <div class="form-group">
			<label for="">Cargo</label>
            <select name="cargo_id" class="form-control form-control-sm">
                @foreach($cargos as $cargo)
                    <option value="{{ $cargo->id }}" {{ ( $cargo->id == $integrante->cargo_id) ? 'selected' :'' }}>{{ $cargo->nombre }}</option>
                @endforeach
            </select>
			<small name="" class="form-text text-muted">Seleccione un cargo, ej: Presidente.</small>
        </div>

        <div class="form-group">
			<label for="">Institución</label>
            <input type="text" class="form-control form-control-sm" value="{{$integrante->institucion}}"
                name="institucion" aria-describedby="Titulo">
			<small name="" class="form-text text-muted">Escriba el nombre de la institución a la que pertenece.</small>
        </div>

        <div class="form-group">
			<label for="">Estado</label>
            <select name="estado" class="form-control form-control-sm">
                @foreach(['Activo','Inactivo'] as $estado)
                    <option value="{{ $estado }}" {{ ( $estado == $integrante->estado) ? 'selected' :'' }}>{{ $estado }}</option>
                @endforeach
            </select>
			<small>
        </div>
        <div class="form-group">
			<label for="">Posición</label>
            <select name="position" class="form-control form-control-sm">
                @php
                    $count = 1
                @endphp
                <option disabled selected>- -</option>
                <option value="1">Al comienzo</option>
                @foreach($integrantes as $int)
                    @if($integrante->id != $int->id)
                    <option value="{{$int->posicion}}">
                        {{ 'Despues de: ('.$int->cargo->nombre.') '.$int->nombres.
                        ' '.$int->apellidos}}</option>
                    @endif
                @endforeach
            </select>
			<small name="" class="form-text text-muted">Seleccione la posición.</small>
        </div>
		<button type="submit" class="btn btn-primary">Editar</button>

		</div>
		</form>
	</div>

  </div>
</div>

@endsection

resources/views/admin/junta/index.blade.php
@extends('admin.template.main')
@section('title','Junta')

@section('contenido')

<br>
<div class="card">
  <div class="card-body">
    <div class="card-title">
        <h5 style="display:inline;">Junta directiva</h5>
        <a href="{{ route('junta.create') }}" class="btn btn-danger btn-sm float-right"
            style="display:inline; margin-left:5px;">
            Agregar integrante</a>
        <a href="javascript:window.history.back();"class="btn btn-success btn-sm" 
            style="display:inline;float:right;">
            Volver
        </a>
      <br><br>
        @include('librerias.error')
      <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Cargo</th>
                <th>Institución</th>
                <th>telefono</th>
                <th>email</th>
                <th>Estado</th>
                <th>Posicion</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach($junta as $integrante)
              @if($integrante->estado == 'Inactivo')
                <tr style="background:#FEE9E5;">
              @else
                <tr>
              @endif
                <td>{{ $integrante->nombres.' '.$integrante->apellidos }}</td>
                <td>{{ $integrante->cargo->nombre }}</td>
                <td>{{ $integrante->institucion }}</td>
                <td>{{ $integrante->telefono }}</td>
                <td>{{ $integrante->email }}</td>
                <td>{{ $integrante->estado }}</td>
                <td>{{ $integrante->posicion }}</td>
                <td>
                    <a href="{{ route('junta.show',$integrante->id) }}" 
                            class="btn btn-outline-secondary btn-sm">Ver</a>

                    <a href="{{ route('junta.edit',$integrante->id) }}" 
                            class="btn btn-outline-success btn-sm">Editar</a>

                    <a href="{{ route('junta.destroy',$integrante->id) }}" 
                            class="btn btn-outline-danger btn-sm" 
                            onclick="return confirm('¿ Esta seguro de eliminar el integrante ?')">
                        Eliminar
                    </a>

                </td>
    
              </tr>
            @endforeach
        </tbody>
      </table>

    </div>

      <hr>


  </div>
</div>


@endsection

resources/views/admin/junta/show.blade.php
@extends('admin.template.main')
@section('title','Junta')

@section('contenido')

<br>
<div class="card">
  <div class="card-body">
    <div class="card-title">
        <h5 style="display:inline;">Junta directiva</h5>
        <a href="javascript:window.history.back();"class="btn btn-success btn-sm" 
            style="display:inline;float:right;">
            Volver
        </a>
        <hr>
        @include('librerias.error')

        <div class="row">
        
        <div class="col-md-6">
            <dt>Nombre:</dt>    
            <dd>{{ $integrante->nombres .' '. $integrante->apellidos }}</dd>

            <hr>

            <dt>Telefono:</dt>
            <dd>{{ $integrante->telefono }}</dd>

            <hr>

            <dt>Institucion:</dt>
            <dd>{{ $integrante->institucion }}</dd>
            
            <hr>
            <dt>Creó:</dt>
            <dd>{{ $integrante->user_create->nombres .' '. $integrante->user_create->apellidos}}
                {{ $integrante->created_at }}
            </dd>

        </div>

        <div class="col-md-6">
            <dt>Cargo:</dt>
            <dd>{{ $integrante->cargo->nombre }}</dd>

            <hr>

            <dt>Email:</dt>
            <dd>{{ $integrante->email }}</dd>

            <hr>

            <dt>Estado:</dt>
            <dd>{{ $integrante->estado }}</dd>

            <hr>
            <dt>Creó:</dt>
            <dd>{{ $integrante->user_update->nombres .' '. $integrante->user_update->apellidos}}
                {{ $integrante->updated_at }}
            </dd>

        </div>

        </div>

    </div>


  </div>
</div>


@endsection